#!/bin/bash
# ============================================================================
# BraanX - SSH and Dropbear Installer
# ============================================================================
# Manages OpenSSH and Dropbear SSH server installations, user accounts,
# SSH-over-WebSocket tunnels, and connection monitoring.
# ============================================================================
# Source: /etc/braanx/lib/functions.sh
# Config: /etc/braanx/braanx.conf
# Database: /etc/braanx/db/braanx.db
# ============================================================================
source /etc/braanx/lib/functions.sh

SSH_CONFIG="/etc/ssh/sshd_config"
SSH_BANNER="/etc/braanx/banner/ssh-banner.txt"
DROPBEAR_DIR="/etc/braanx/dropbear"
WS_SSH_PORT=2222
BRAANX_CONF="/etc/braanx/braanx.conf"
BRAANX_DB="/etc/braanx/db/braanx.db"
SSH_USERS_FILE="/etc/braanx/ssh-users"

# ----------------------------------------------------------------------------
# install_ssh() - Install and configure OpenSSH server
# ----------------------------------------------------------------------------
install_ssh() {
    msg_info "Installing OpenSSH server..."
    pkg_install openssh-server

    # Backup original config
    cp -f "${SSH_CONFIG}" "${SSH_CONFIG}.bak" 2>/dev/null

    # Generate SSH host keys if missing
    if [[ ! -f /etc/ssh/ssh_host_rsa_key ]]; then
        msg_info "Generating RSA host key..."
        ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" -q
    fi
    if [[ ! -f /etc/ssh/ssh_host_ecdsa_key ]]; then
        msg_info "Generating ECDSA host key..."
        ssh-keygen -t ecdsa -b 256 -f /etc/ssh/ssh_host_ecdsa_key -N "" -q
    fi
    if [[ ! -f /etc/ssh/ssh_host_ed25519_key ]]; then
        msg_info "Generating ED25519 host key..."
        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -q
    fi

    # Create banner directory and file
    mkdir -p /etc/braanx/banner
    _create_ssh_banner

    # Write sshd_config
    msg_info "Configuring sshd..."
    local port
    port=$(config_get "SSH_PORT")
    [[ -z "${port}" ]] && port=22

    cat > "${SSH_CONFIG}" << EOF
# BraanX - SSH Server Configuration
# Auto-generated by BraanX installer

Port ${port}
AddressFamily inet
ListenAddress 0.0.0.0

# Protocol settings
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Authentication
PermitRootLogin yes
MaxAuthTries 3
MaxSessions 10
LoginGraceTime 30
StrictModes no

# Password and key authentication
PermitRootLogin yes
PasswordAuthentication yes
PubkeyAuthentication yes
ChallengeResponseAuthentication no
KbdInteractiveAuthentication no
UsePAM no

# Disable unused features
X11Forwarding no
PrintMotd no
AcceptEnv LANG LC_*

# Banner
Banner ${SSH_BANNER}

# Security hardening
PermitEmptyPasswords no
ClientAliveInterval 60
ClientAliveCountMax 3
TCPKeepAlive yes

# Disable tunneling by default (VPN users should not port-forward)
AllowTcpForwarding no
PermitTunnel no
GatewayPorts no
EOF

    # Restart SSH
    systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null
    systemctl enable sshd 2>/dev/null || systemctl enable ssh 2>/dev/null

    msg_ok "OpenSSH server installed and configured on port ${port}"
}

# ----------------------------------------------------------------------------
# _create_ssh_banner() - Generate SSH login banner
# ----------------------------------------------------------------------------
_create_ssh_banner() {
    local domain
    local ip_addr
    domain=$(config_get "DOMAIN")
    ip_addr=$(get_public_ip)

    cat > "${SSH_BANNER}" << EOF

   ______           __     __              __  __
  / ____/___  _____/ /_   / /_  ____      / / / /___  _ __
 / /   / __ \\/ ___/ __ \\ / __ \\/ __ \\    / /_/ / __ \\| '_ \\
/ /___/ /_/ / /  / / / // /_/ / /_/ /   / __  / /_/ /| | | |
\\____/\\____/_/  /_/ /_/\\____/\\____/   /_/ /_/\\____/ |_| |_|

  SSH Server
  Server: ${domain:-${ip_addr}}
EOF
}

# ----------------------------------------------------------------------------
# install_dropbear() - Install and configure Dropbear SSH server
# ----------------------------------------------------------------------------
install_dropbear() {
    msg_info "Installing Dropbear SSH server..."
    pkg_install dropbear

    mkdir -p "${DROPBEAR_DIR}"

    # Generate host keys for Dropbear
    if [[ ! -f "${DROPBEAR_DIR}/dropbear_rsa_host_key" ]]; then
        dropbearkey -t rsa -s 2048 -f "${DROPBEAR_DIR}/dropbear_rsa_host_key" &>/dev/null
        msg_info "Generated Dropbear RSA key"
    fi
    if [[ ! -f "${DROPBEAR_DIR}/dropbear_ecdsa_host_key" ]]; then
        dropbearkey -t ecdsa -s 256 -f "${DROPBEAR_DIR}/dropbear_ecdsa_host_key" &>/dev/null
        msg_info "Generated Dropbear ECDSA key"
    fi
    if [[ ! -f "${DROPBEAR_DIR}/dropbear_ed25519_host_key" ]]; then
        dropbearkey -t ed25519 -f "${DROPBEAR_DIR}/dropbear_ed25519_host_key" &>/dev/null
        msg_info "Generated Dropbear ED25519 key"
    fi

    # Create systemd service for port 143
    _create_dropbear_service 143 "dropbear-143" "Dropbear SSH on port 143"

    # Create systemd service for port 109
    _create_dropbear_service 109 "dropbear-109" "Dropbear SSH on port 109"

    systemctl daemon-reload
    systemctl enable dropbear-143 dropbear-109 &>/dev/null
    systemctl start dropbear-143 dropbear-109 &>/dev/null

    msg_ok "Dropbear installed on ports 143 and 109"
}

# ----------------------------------------------------------------------------
# _create_dropbear_service() - Generate a systemd unit for Dropbear on a port
#   $1 = port
#   $2 = unit name
#   $3 = description
# ----------------------------------------------------------------------------
_create_dropbear_service() {
    local port="${1}"
    local name="${2}"
    local desc="${3}"
    local service_path="/etc/systemd/system/${name}.service"

    cat > "${service_path}" << EOF
[Unit]
Description=${desc}
After=network.target

[Service]
Type=simple
ExecStart=/usr/sbin/dropbear \\
    -E \\
    -p ${port} \\
    -r ${DROPBEAR_DIR}/dropbear_rsa_host_key \\
    -r ${DROPBEAR_DIR}/dropbear_ecdsa_host_key \\
    -r ${DROPBEAR_DIR}/dropbear_ed25519_host_key \\
    -b ${SSH_BANNER} \\
    -G 0 \\
    -N 0
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
}

# ----------------------------------------------------------------------------
# install_ssh_websocket() - Set up SSH-over-WebSocket tunnel
# ----------------------------------------------------------------------------
install_ssh_websocket() {
    msg_info "Installing SSH-over-WebSocket support..."

    # Install websockify
    pkg_install websockify python3-pip 2>/dev/null

    # Try pip install if websockify not available via package manager
    if ! command -v websockify &>/dev/null; then
        pip3 install websockify 2>/dev/null || pip install websockify 2>/dev/null
    fi

    if ! command -v websockify &>/dev/null; then
        msg_err "Failed to install websockify"
        return 1
    fi

    local ws_port
    ws_port=${WS_SSH_PORT}

    # Create systemd service for WS-SSH
    cat > /etc/systemd/system/ws-ssh.service << EOF
[Unit]
Description=BraanX SSH-over-WebSocket (websockify)
After=network.target sshd.service

[Service]
Type=simple
ExecStart=/usr/bin/websockify --daemon ${ws_port} 127.0.0.1:22
ExecStartPre=/bin/sleep 2
Restart=always
RestartSec=5
User=nobody

[Install]
WantedBy=multi-user.target
EOF

    # Alternative: direct websockify without daemon flag
    which websockify &>/dev/null && {
        local ws_path
        ws_path=$(command -v websockify)
        cat > /etc/systemd/system/ws-ssh.service << EOF
[Unit]
Description=BraanX SSH-over-WebSocket (websockify)
After=network.target sshd.service

[Service]
Type=simple
ExecStart=${ws_path} ${ws_port} 127.0.0.1:22
Restart=always
RestartSec=5
User=nobody
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF
    }

    systemctl daemon-reload
    systemctl enable ws-ssh &>/dev/null
    systemctl start ws-ssh

    if systemctl is-active --quiet ws-ssh; then
        msg_ok "SSH-over-WebSocket running on port ${ws_port} (proxies to localhost:22)"
    else
        msg_warn "ws-ssh service may not have started correctly - check logs"
    fi

    msg_info "Nginx will proxy /ssh-ws on port 443/80 to this service"
}

# ----------------------------------------------------------------------------
# add_ssh_account() - Create a new SSH user
#   $1 = username
#   $2 = password
#   $3 = days (account validity)
# ----------------------------------------------------------------------------
add_ssh_account() {
    local username="${1}"
    local password="${2}"
    local days="${3}"

    if [[ -z "${username}" || -z "${password}" || -z "${days}" ]]; then
        msg_err "Usage: add_ssh_account <username> <password> <days>"
        return 1
    fi

    # Check for existing user
    if id -u "${username}" &>/dev/null; then
        msg_err "User '${username}' already exists on system"
        return 1
    fi

    # Check for duplicate in database
    local exists
    exists=$(db_query "SELECT username FROM ssh_users WHERE username='${username}' AND active=1")
    if [[ -n "${exists}" ]]; then
        msg_err "SSH user '${username}' already exists in database"
        return 1
    fi

    msg_info "Creating SSH user: ${username}..."

    # Create Linux user with restricted shell
    useradd -m -s /bin/bash "${username}"
    if [[ $? -ne 0 ]]; then
        msg_err "Failed to create user '${username}'"
        return 1
    fi

    # Set password
    echo "${username}:${password}" | chpasswd
    if [[ $? -ne 0 ]]; then
        msg_err "Failed to set password for '${username}'"
        userdel -r "${username}" 2>/dev/null
        return 1
    fi

    # Set account expiry
    local expires_at
    expires_at=$(date -d "+${days} days" +%Y-%m-%d 2>/dev/null || date -v+${days}d +%Y-%m-%d 2>/dev/null)
    [[ -z "${expires_at}" ]] && expires_at=$(date +%Y-%m-%d)
    chage -E "${expires_at}" "${username}" 2>/dev/null

    # Insert into database
    db_query "INSERT INTO ssh_users (username, password, days, created_at, expires_at, active)
              VALUES ('${username}', '${password}', ${days}, datetime('now','localtime'), '${expires_at}', 1)"

    # Append to tracking file
    mkdir -p "$(dirname "${SSH_USERS_FILE}")"
    echo "${username}" >> "${SSH_USERS_FILE}"

    # Show user info
    local domain
    local ip_addr
    domain=$(config_get "DOMAIN")
    ip_addr=$(get_public_ip)

    draw_header "SSH ACCOUNT CREATED"
    draw_table \
        "Username" "${username}" \
        "Password" "${password}" \
        "Valid Days" "${days}" \
        "Expires" "${expires_at}" \
        "SSH Port" "$(config_get SSH_PORT:-22)" \
        "Dropbear Ports" "143, 109" \
        "WS-SSH Path" "/ssh-ws (port 443)"

    msg_ok "SSH user '${username}' created successfully"
}

# ----------------------------------------------------------------------------
# delete_ssh_account() - Remove an SSH user
#   $1 = username
# ----------------------------------------------------------------------------
delete_ssh_account() {
    local username="${1}"

    if [[ -z "${username}" ]]; then
        msg_err "Usage: delete_ssh_account <username>"
        return 1
    fi

    if ! id -u "${username}" &>/dev/null; then
        msg_warn "User '${username}' does not exist on system"
    else
        # Kill all user processes
        pkill -u "${username}" &>/dev/null

        # Remove user and home directory
        userdel -r "${username}" 2>/dev/null
        if [[ $? -eq 0 ]]; then
            msg_info "System user '${username}' removed"
        else
            msg_warn "Failed to fully remove user '${username}'"
        fi
    fi

    # Deactivate in database
    db_query "UPDATE ssh_users SET active=0 WHERE username='${username}'"

    # Remove from tracking file
    if [[ -f "${SSH_USERS_FILE}" ]]; then
        sed -i "/^${username}$/d" "${SSH_USERS_FILE}"
    fi

    msg_ok "SSH user '${username}' deleted"
}

# ----------------------------------------------------------------------------
# list_ssh_accounts() - Show all active SSH users
# ----------------------------------------------------------------------------
list_ssh_accounts() {
    msg_info "Active SSH Accounts:"
    local accounts
    accounts=$(db_query "SELECT username, days, created_at, expires_at FROM ssh_users WHERE active=1 ORDER BY id")

    if [[ -z "${accounts}" ]]; then
        msg_warn "No active SSH accounts found"
        return 0
    fi

    echo ""
    printf "${BOLD}%-15s %-8s %-20s %-12s${RST}\n" "USERNAME" "DAYS" "CREATED" "EXPIRES"
    printf "${Y}%-s${RST}\n" "$(printf '%.0s-' {1..60})"
    echo "${accounts}" | while IFS='|' read -r user days created exp; do
        printf "%-15s %-8s %-20s %-12s\n" "${user}" "${days}" "${created}" "${exp}"
    done
    echo ""
}

# ----------------------------------------------------------------------------
# ssh_restart() - Restart all SSH-related services
# ----------------------------------------------------------------------------
ssh_restart() {
    msg_info "Restarting SSH services..."

    systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null
    systemctl restart dropbear-143 2>/dev/null
    systemctl restart dropbear-109 2>/dev/null
    systemctl restart ws-ssh 2>/dev/null

    msg_ok "All SSH services restarted"
}

# ----------------------------------------------------------------------------
# ssh_status() - Display SSH service status and connected users
# ----------------------------------------------------------------------------
ssh_status() {
    draw_header "SSH SERVICE STATUS"

    # SSH (sshd) status
    local ssh_status
    ssh_status=$(systemctl is-active sshd 2>/dev/null || systemctl is-active ssh 2>/dev/null)
    msg_info "OpenSSH (port $(config_get SSH_PORT:-22)): ${ssh_status}"

    # Dropbear status
    local db143
    local db109
    db143=$(systemctl is-active dropbear-143 2>/dev/null)
    db109=$(systemctl is-active dropbear-109 2>/dev/null)
    msg_info "Dropbear port 143: ${db143}"
    msg_info "Dropbear port 109: ${db109}"

    # WS-SSH status
    local ws_ssh
    ws_ssh=$(systemctl is-active ws-ssh 2>/dev/null)
    msg_info "SSH-over-WebSocket (port ${WS_SSH_PORT}): ${ws_ssh}"

    echo ""
    msg_info "Currently logged in users:"
    who 2>/dev/null | while read line; do
        echo "  ${line}"
    done

    # Show active SSH connections
    echo ""
    msg_info "Active SSH connections:"
    local conn_count
    conn_count=$(ss -tnp 2>/dev/null | rg -c ':22\b' 2>/dev/null || echo "0")
    ss -tnp 2>/dev/null | rg ':22\b' | head -20 | while read line; do
        echo "  ${line}"
    done
    echo ""
    msg_info "Total active SSH connections: ${conn_count}"

    # Account summary
    local total
    total=$(db_query "SELECT COUNT(*) FROM ssh_users WHERE active=1" 2>/dev/null)
    msg_info "Total active SSH accounts: ${total:-0}"
    echo ""
}

# ----------------------------------------------------------------------------
# _init_ssh_db() - Initialize the SSH users database table
# ----------------------------------------------------------------------------
_init_ssh_db() {
    db_query "CREATE TABLE IF NOT EXISTS ssh_users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL,
        days INTEGER NOT NULL,
        created_at TEXT DEFAULT (datetime('now','localtime')),
        expires_at TEXT,
        active INTEGER DEFAULT 1
    )"
}

# ============================================================================
# Export all functions
# ============================================================================
export -f install_ssh
export -f install_dropbear
export -f install_ssh_websocket
export -f add_ssh_account
export -f delete_ssh_account
export -f list_ssh_accounts
export -f ssh_restart
export -f ssh_status
export -f _create_ssh_banner
export -f _create_dropbear_service
export -f _init_ssh_db
